### ISSUE TITLE
Creating a DB instance directly

### ISSUE THREAD

**Issue by tranlm** [ksanman/ChromaDBSharp#1]
Hi,

thanks for putting this together. I’m wondering: the Python client allows me to create a DB and instance within the python call (rather than hooking up to a separate DB host). Does this code allow me to do the same? 

Thanks!

**Comment by tranlm** [comment]
Looking through the code, I've confirmed that the entire library has been set up only for the httpClient. Will need to be refactored to abstract to a general ClientAPI before we can set up local or persistent DBs. Closing the ticket for now.

**Comment by ksanman** [comment]
It is not possible to do an "in memory" chromadb in c# like the python client because the actual chromadb code is in python. This library is similar to the JavaScript client.
