### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0 after deploying on IIS

### ISSUE THREAD

**Issue by jdoradoscripta** [ksanman/ChromaDBSharp#2]
Thank you for your great work!. After deploying my app, I'm getting an exception "Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=8.0.0.0. The system cannot find the file specified". This is launched after deploying on IIS. The wrapper works fine in debug, but the application does not load on IIS. I'm using .NET core 7.0  as target platform. Other developers had the same issue with this dependency and they suggest that downgrading "Microsoft.Extensions.Http" solved the issue "https://stackoverflow.com/questions/74808187/could-not-load-file-or-assembly-microsoft-extensions-configuration-abstractions".

**Comment by ksanman** [comment]
I created a net 7 app and deployed to IIS both InProcess and OutProcess and did not get any errors. Have you tried updating all packages in the project to the latest versions.?

Since NET 7 has already reached end of support, I'm not too inclined to down grade versions.

**Comment by jdoradoscripta** [comment]
> I created a net 7 app and deployed to IIS both InProcess and OutProcess and did not get any errors. Have you tried updating all packages in the project to the latest versions.?
> 
> Since NET 7 has already reached end of support, I'm not too inclined to down grade versions.

I updated all my packages on my application and it is working now on IIS. Thanks!
